# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ce4da9858c748c19f9ef9eb80dfdb8293f99b70dd609078bb3cb1cdf97396f4364ed43e6ec4b48930555b187dfac2aedebdcb12b0b65b26a018f96be9f1d63

test:
  secret_key_base: c0ebbae2b623eb1231c1dbfadcff47e8c33ba365819bd13a6f09885c857972eb7875f8bd9db963c7975de6b50cdd072bfdb09f31fa141c435b498bd47a5099be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
